"use strict";

const ORGS = [
{n:"Food Lifeline",r:"north",a:"Shoreline & Seattle",c:["hunger"],u:"https://foodlifeline.org",d:"Rescues surplus food and supplies 300+ food programs across Western WA. Sort-and-pack shifts at the Hunger Solution Center."},
{n:"Northwest Harvest",r:"regional",a:"Statewide (Kent warehouse)",c:["hunger"],u:"https://www.nwharvest.org",d:"Supplies a statewide network of food banks. Volunteer repack sessions at the Kent distribution center."},
{n:"United Way of King County",r:"regional",a:"King County",c:["hunger","justice"],u:"https://uwkc.org",d:"Free tax-prep (VITA) volunteers, benefits navigation and food-security initiatives."},
{n:"Ballard Food Bank",r:"seattle",a:"Ballard",c:["hunger"],u:"https://www.ballardfoodbank.org",d:"Grocery-style food bank serving Northwest Seattle — shopping assistants, drivers, warehouse crews."},
{n:"FamilyWorks",r:"seattle",a:"U District / Wallingford",c:["hunger","youth"],u:"https://familyworksseattle.org",d:"Food bank plus family resource center — food sorting, WIC support and play-group help."},
{n:"West Seattle Food Bank",r:"seattle",a:"West Seattle",c:["hunger"],u:"https://westseattlefoodbank.org",d:"Neighborhood food bank with home delivery for homebound neighbors — drivers needed."},
{n:"White Center Food Bank",r:"south",a:"White Center",c:["hunger"],u:"https://whitecenterfoodbank.org",d:"High-volume neighborhood food bank — intake, shopping floor and stock shifts."},
{n:"The Storehouse WA",r:"north",a:"Woodinville",c:["hunger"],u:"https://thestorehousewa.org",d:"Woodinville's food bank and clothing bank, serving the Northshore corridor."},
{n:"Tukwila Pantry",r:"south",a:"Tukwila",c:["hunger"],u:"https://tukwilapantry.org",d:"Serves one of the most diverse zip codes in the US — multilingual volunteers especially valued."},
{n:"Kent Food Bank & Emergency Services",r:"south",a:"Kent",c:["hunger"],u:"https://kentfoodbank.org",d:"City-supported food bank and emergency assistance office."},
{n:"The Auburn Food Bank",r:"south",a:"Auburn",c:["hunger"],u:"https://www.theauburnfoodbank.org",d:"South King County staple since 1929 — client check-in, sorting and delivery roles."},
{n:"Multi-Service Center",r:"south",a:"Federal Way & Lakewood",c:["hunger","housing"],u:"https://mscfw.org",d:"Food bank, housing and employment programs serving South King County."},
{n:"Hopelink",r:"eastside",a:"Bellevue · Kirkland · Redmond · Shoreline",c:["hunger","housing","seniors"],u:"https://www.hope-link.org",d:"Eastside's largest nonprofit — five service centers, food banks, shelter and transportation."},
{n:"FareStart",r:"seattle",a:"Downtown Seattle",c:["hunger","justice"],u:"https://www.farestart.org",d:"Culinary job training for people overcoming homelessness — kitchen helpers, café baristas, event crews."},
{n:"Mary's Place",r:"seattle",a:"Seattle (multiple shelters)",c:["housing","hunger"],u:"https://www.marysplaceseattle.org",d:"No child sleeps outside — family shelters need meal teams, drive organizers and kid activity leads."},
{n:"Union Gospel Mission",r:"seattle",a:"Seattle",c:["housing","hunger"],u:"https://www.ugmseattle.org",d:"Meals, shelter and recovery programs — serve dinner, mentor, or join search & rescue outreach in winter."},
{n:"YouthCare",r:"seattle",a:"Seattle",c:["youth","housing"],u:"https://youthcare.org",d:"Housing, education and employment for young people experiencing homelessness."},
{n:"ROOTS Young Adult Shelter",r:"seattle",a:"U District",c:["housing","youth"],u:"https://rootsinfo.org",d:"Overnight shelter for 18–25 year olds — evening meal servers and overnight hosts."},
{n:"Teen Feed",r:"seattle",a:"University District",c:["youth","hunger"],u:"https://teenfeed.org",d:"Hot meals for street-involved youth — meal teams, supplies coordination."},
{n:"DESC",r:"seattle",a:"Downtown Seattle",c:["housing","health"],u:"https://www.desc.org",d:"The region's largest supportive-housing provider — occasional project and event volunteering."},
{n:"Facing Homelessness",r:"seattle",a:"Seattle",c:["housing","justice"],u:"https://www.facinghomelessness.org",d:"Community storytelling (The 'Just Say Hello' movement) — photography, Jeff's List fulfilment."},
{n:"Real Change",r:"seattle",a:"Seattle",c:["justice"],u:"https://www.realchangewa.org",d:"Street newspaper employed by vendors — outreach and vendor support roles."},
{n:"Recovery Café",r:"seattle",a:"SoDo & Eastside",c:["health","community"],u:"https://www.recoverycafe.org",d:"Belonging community for people in recovery from addiction — café shifts, kitchen, welcome desk."},
{n:"YWCA Seattle | King | Snohomish",r:"regional",a:"King & Snohomish Counties",c:["dv","housing"],u:"https://www.ywcaworks.org",d:"Emergency shelter, housing and employment programs for women and families."},
{n:"The Sophia Way",r:"eastside",a:"Bellevue & Kirkland",c:["dv","housing"],u:"https://sophiaway.org",d:"Eastside women's shelter and day center — meal sponsors, overnight support."},
{n:"Congregations for the Homeless",r:"eastside",a:"Eastside",c:["housing"],u:"https://cfhomeless.org",d:"Men's shelter and permanent housing pipeline on the Eastside."},
{n:"Jubilee Women's Center",r:"eastside",a:"Bellevue",c:["housing","dv"],u:"https://jubileewomen.org",d:"Transitional housing for women — handyman days, career mentors, garden crews."},
{n:"LifeWire",r:"eastside",a:"Bellevue",c:["dv"],u:"https://lifewire.org",d:"Domestic violence services for Eastsiders — advocacy, housing and children's programs."},
{n:"New Beginnings",r:"seattle",a:"Seattle",c:["dv"],u:"https://newbegin.org",d:"Domestic violence shelter and legal advocacy — community education volunteers."},
{n:"API Chaya",r:"seattle",a:"Seattle",c:["dv","refugees"],u:"https://www.apichaya.org",d:"Supports survivors of gender violence in Asian, South Asian and Pacific Islander communities."},
{n:"Atlantic Street Center",r:"seattle",a:"Southeast Seattle",c:["youth","health"],u:"https://atlanticstreetcenter.org",d:"Education, family support and violence prevention in Southeast Seattle and Tukwila."},
{n:"Wellspring Family Services",r:"seattle",a:"Seattle",c:["housing","youth"],u:"https://wellspringfs.org",d:"Prevents family homelessness — Baby Boutique sorting, housing stabilization."},
{n:"Solid Ground",r:"regional",a:"King County",c:["housing","justice"],u:"https://www.solidground.org",d:"Housing, food and transportation justice programs across the county."},
{n:"Neighborhood House",r:"seattle",a:"West Seattle & King County",c:["education","hunger"],u:"https://nhwa.org",d:"Head Start, food security and employment support, rooted in public housing communities."},
{n:"El Centro de la Raza",r:"seattle",a:"Beacon Hill",c:["refugees","youth","education"],u:"https://www.elcentrodelaraza.org",d:"Beloved Beacon Hill institution — tutors, food programs, advocacy, event days."},
{n:"ACRS (Asian Counseling & Referral Service)",r:"seattle",a:"Seattle",c:["health","refugees","seniors"],u:"https://acrs.org",d:"Behavioral health and human services for Asian Americans and Pacific Islanders."},
{n:"Chinese Information & Service Center",r:"seattle",a:"Chinatown-International District",c:["refugees","seniors","youth"],u:"https://www.cisc-seattle.org",d:"Bilingual family support, after-school programs and senior wellness."},
{n:"ReWA (Refugee Women's Alliance)",r:"seattle",a:"Seattle",c:["refugees"],u:"https://rewa.org",d:"Refugee & immigrant families — ESL classroom aides, youth programs, donation drives."},
{n:"Kin On",r:"seattle",a:"Seattle (Chinatown-ID)",c:["seniors","health"],u:"https://kinon.org",d:"Culturally-competent senior care for Chinese elders — companionship, events, fundraising walks."},
{n:"Jewish Family Service",r:"regional",a:"Seattle & Eastside",c:["seniors","refugees","hunger"],u:"https://jfsseattle.org",d:"Polack Food Bank, refugee resettlement, senior transportation — big volunteer program."},
{n:"Catholic Community Services",r:"regional",a:"Western Washington",c:["housing","seniors","health"],u:"https://ccsww.org",d:"Massive safety-net agency — shelter volunteers, meal service, immigrant assistance."},
{n:"International Rescue Committee (Sea-Tac)",r:"south",a:"Tukwila / Sea-Tac",c:["refugees"],u:"https://www.rescue.org/united-states/seattle-wa",d:"Resets newly-arrived refugees — apartment setups, airport welcomes, job coaching."},
{n:"World Relief Western Washington",r:"south",a:"Kent",c:["refugees"],u:"https://worldrelief.org/western-washington/",d:"Good-neighbor teams, co-sponsorships, ESL conversation partners for newcomers."},
{n:"Northwest Immigrant Rights Project",r:"seattle",a:"Seattle & Granger",c:["justice","refugees"],u:"https://www.nwirp.org",d:"Legal aid for immigrants — interpreters, legal assistants and community outreach."},
{n:"OneAmerica",r:"seattle",a:"Statewide",c:["justice","refugees"],u:"https://weareoneamerica.org",d:"Immigrant-rights advocacy — civic engagement drives and community events."},
{n:"Casa Latina",r:"seattle",a:"Central District",c:["justice","education"],u:"https://casa-latina.org",d:"Worker center empowering Latino immigrants — ESL classes, day-center support."},
{n:"Chief Seattle Club",r:"seattle",a:"Pioneer Square",c:["housing","justice"],u:"https://chiefseattleclub.org",d:"Housing and services for urban Native people — ĉaw pəł health center volunteers."},
{n:"United Indians of All Tribes",r:"seattle",a:"Discovery Park",c:["arts","community","youth"],u:"https://www.unitedindians.org",d:"Daybreak Star Cultural Center — powwow help, cultural events, early-learning support."},
{n:"Kandelia",r:"seattle",a:"Little Saigon / CID",c:["refugees","youth"],u:"https://kandelia.org",d:"After-school and workforce programs for immigrant & refugee youth."},
{n:"Seattle Humane",r:"eastside",a:"Bellevue",c:["animals"],u:"https://www.seattlehumane.org",d:"One of the region's biggest shelters — dog walking, cat socializing, foster homes."},
{n:"PAWS",r:"north",a:"Lynnwood",c:["animals"],u:"https://www.paws.org",d:"Companion animals AND wildlife rehabilitation — animal care, wildlife feeding shifts."},
{n:"Homeward Pet Adoption Center",r:"north",a:"Woodinville",c:["animals"],u:"https://homewardpet.org",d:"No-kill adoption center — kennel crews, dog walkers, event volunteers."},
{n:"Seattle Animal Shelter",r:"seattle",a:"Interbay",c:["animals"],u:"https://www.seattle.gov/animal-shelter",d:"City shelter — dog walking, foster network, adoption events."},
{n:"Woodland Park Zoo",r:"seattle",a:"Phinney Ridge",c:["animals","arts"],u:"https://www.zoo.org",d:"ZooCorps teens, docents and event volunteers at one of America's top zoos."},
{n:"Seattle Aquarium",r:"seattle",a:"Waterfront",c:["animals","education"],u:"https://www.seattleaquarium.org",d:"Beach naturalists and visitor-engagement volunteers on Pier 59."},
{n:"The Museum of Flight",r:"south",a:"Tukwila / Boeing Field",c:["arts","education"],u:"https://www.museumofflight.org",d:"Docents, gallery hosts and restoration shop volunteers among real aircraft."},
{n:"Pacific Science Center",r:"seattle",a:"Seattle Center",c:["education","arts"],u:"https://www.pacificsciencecenter.org",d:"Exhibit interpreters and special-event crews under the arches."},
{n:"KidsQuest Children's Museum",r:"eastside",a:"Bellevue",c:["education","arts"],u:"https://www.kidsquestmuseum.org",d:"Hands-on play museum — exhibit guides and party helpers."},
{n:"Studio East",r:"eastside",a:"Kirkland",c:["arts","youth"],u:"https://studio-east.org",d:"Children's theater company — sets, costumes, box office for young performers."},
{n:"Bellevue Botanical Garden",r:"eastside",a:"Bellevue",c:["enviro","arts"],u:"https://www.bellevuebotanical.org",d:"33-acre garden run with volunteer docents, grounds crews and the dahlia display."},
{n:"21 Acres",r:"north",a:"Woodinville",c:["enviro","hunger"],u:"https://21acres.org",d:"Sustainable farm & LEED campus — field work, market days, kitchen events."},
{n:"Oxbow Farm & Conservation Center",r:"north",a:"Carnation",c:["enviro","education"],u:"https://oxbow.org",d:"Organic farm and conservation hub — planting days and school-tour guides."},
{n:"Tilth Alliance",r:"seattle",a:"Wallingford",c:["enviro","hunger"],u:"https://tilthalliance.org",d:"Community gardens and farm education — work parties teach sustainable food growing."},
{n:"EarthCorps",r:"regional",a:"Puget Sound",c:["enviro"],u:"https://earthcorps.org",d:"Crew-based environmental restoration — plant trees, remove invasives, all gear provided."},
{n:"Mountains to Sound Greenway Trust",r:"regional",a:"I-90 Corridor",c:["enviro"],u:"https://mtsgreenway.org",d:"Forest and trail restoration along the I-90 Greenway — great corporate & group outings."},
{n:"Washington Trails Association",r:"regional",a:"Statewide",c:["enviro"],u:"https://www.wta.org",d:"Trail work parties everywhere from Discovery Park to the Cascades — no experience needed."},
{n:"Washington Native Plant Society",r:"regional",a:"Central PugetSound chapter",c:["enviro"],u:"https://www.wnps.org",d:"Plant sales, restoration projects and native-garden stewardship."},
{n:"Green Seattle Partnership",r:"seattle",a:"All Seattle parks",c:["enviro"],u:"https://www.greenseattle.org",d:"Restore 2,500 acres of urban forest — become a Forest Steward for your local park."},
{n:"King County Parks",r:"regional",a:"Countywide trails",c:["enviro","community"],u:"https://kingcounty.gov/parks",d:"Trail repairs and event support across 200+ parks including regional trail corridors."},
{n:"Forterra",r:"regional",a:"Puget Sound",c:["enviro"],u:"https://forterra.org",d:"Land conservation across the region — stewardship events on protected lands."},
{n:"The Nature Conservancy in Washington",r:"regional",a:"Statewide",c:["enviro"],u:"https://www.nature.org/en-us/about-us/where-we-work/united-states/washington/",d:"Work parties and citizen-science on preserves like Port Susan Bay."},
{n:"Conservation Northwest",r:"regional",a:"Statewide",c:["enviro","animals"],u:"https://conservationnw.org",d:"Keeps the Northwest wild — habitat restoration weekends connecting North Cascades habitat."},
{n:"Seattle Public Library",r:"seattle",a:"27 neighborhood branches",c:["education","community"],u:"https://www.spl.org",d:"Study Zone tutors, ESL conversation groups, Friends of the Library book sales."},
{n:"Literacy Source",r:"seattle",a:"Lake City",c:["education"],u:"https://www.literacy-source.org",d:"Adult literacy and ESL tutoring — full training provided, no teaching background needed."},
{n:"Page Ahead",r:"regional",a:"Puget Sound",c:["education","youth"],u:"https://pageahead.org",d:"Gets books into the hands of kids in need — book drives and distribution days."},
{n:"Bureau of Fearless Ideas",r:"seattle",a:"Greater Seattle",c:["education","youth"],u:"https://fearlessideas.org",d:"Writing centers where volunteer tutors help kids write and publish wild stories."},
{n:"Technology Access Foundation",r:"seattle",a:"Seattle & Kent",c:["education","youth"],u:"https://www.techaccess.org",d:"STEM education for students of color — mentors, coaches and judges for student showcases."},
{n:"Treehouse",r:"regional",a:"King County",c:["youth","justice"],u:"https://treehouseforkids.org",d:"For youth in foster care — academic tutors, Wearhouse sorting, donation drives."},
{n:"Big Brothers Big Sisters Puget Sound",r:"regional",a:"King & Pierce Counties",c:["youth"],u:"https://inspirebig.org",d:"One-to-one mentoring — a few hours twice a month changes a kid's trajectory."},
{n:"Boys & Girls Clubs of King County",r:"regional",a:"12+ club locations",c:["youth"],u:"https://positiveplace.org",d:"After-school programs — homework help, coaching, smart girls & stem clubs."},
{n:"YMCA of Greater Seattle",r:"regional",a:"King & Snohomish",c:["youth","health","community"],u:"https://www.seattleymca.org",d:"Youth sports coaching, camp counseling, event support at 13 branches."},
{n:"Friends of Youth",r:"eastside",a:"Redmond, Duvall & Eastside",c:["youth","housing"],u:"https://www.friendsofyouth.org",d:"Foster support, youth shelters and counseling across the Eastside."},
{n:"Youth Eastside Services",r:"eastside",a:"Bellevue · Kirkland · Redmond",c:["youth","health"],u:"https://youtheastsideservices.org",d:"Counseling and prevention programs — event committees, outreach help."},
{n:"Eastside Baby Corner",r:"eastside",a:"Issaquah (serves all Eastside)",c:["hunger","youth"],u:"https://babycorner.org",d:"Diapers, beds and essentials for Eastside kids — weekly packing shifts, diaper drives."},
{n:"Sound Generations",r:"regional",a:"King County",c:["seniors"],u:"https://soundgenerations.org",d:"Meals on Wheels drivers urgently wanted — plus senior center activity helpers."},
{n:"Homage Senior Services",r:"north",a:"Snohomish County",c:["seniors"],u:"https://homage.org",d:"Meals on Wheels, senior companionship and benefits assistance in Snohomish County."},
{n:"NAMI Seattle",r:"seattle",a:"Seattle",c:["health","justice"],u:"https://namiseattle.org",d:"Mental health advocacy — peer program support, awareness events, office help."},
{n:"Crisis Connections",r:"regional",a:"King County",c:["health"],u:"https://www.crisisconnections.org",d:"Answer the crisis line or Teen Link — comprehensive training, remote options available."},
{n:"Bloodworks Northwest",r:"regional",a:"Puget Sound",c:["health"],u:"https://www.bloodworksnw.org",d:"Blood drive ambassadors, canteen hosts and donor-center greeters."},
{n:"American Red Cross Northwest",r:"regional",a:"WA & Alaska",c:["health","community"],u:"https://www.redcross.org/local/washington.html",d:"Disaster response teams, blood-drive support, smoke-alarm installation canvasses."},
{n:"Seattle/King County Clinic",r:"regional",a:"Seattle Center (annual)",c:["health","community"],u:"https://seattlekingcountyclinic.org",d:"Massive annual free clinic — hundreds of clinical AND general volunteers needed each year."},
{n:"Overlake Medical Center",r:"eastside",a:"Bellevue",c:["health"],u:"https://www.overlakehospital.org",d:"Hospital volunteer program — information desks, patient transport, gift shop."},
{n:"EvergreenHealth",r:"eastside",a:"Kirkland",c:["health"],u:"https://www.evergreenhealth.com",d:"Volunteer program with 30+ roles from guest services to pet-therapy teams."},
{n:"Cascade Bicycle Club",r:"seattle",a:"Seattle",c:["community","enviro"],u:"https://www.cascade.org",d:"Ride marshals and event crews for Chilly Hilly, STP and free group rides."},
{n:"Bike Works",r:"seattle",a:"Columbia City",c:["community","youth"],u:"https://bikeworks.org",d:"Community bike shop — repair nights, youth earn-a-bike mentoring, donation triage."},
{n:"Seattle Works",r:"seattle",a:"Seattle",c:["community"],u:"https://seattleworks.org",d:"Matches busy people with one-off volunteer events and nonprofit board service."},
{n:"League of Women Voters of Seattle",r:"regional",a:"King County",c:["justice","community"],u:"https://www.lwvseattle.org",d:"Nonpartisan voter registration, candidate forums and election info fairs."},
{n:"ACLU of Washington",r:"seattle",a:"Statewide",c:["justice"],u:"https://www.aclu-wa.org",d:"Civil liberties advocacy — event volunteers, community ambassadors, legislative alerts."},
{n:"Pike Place Market Foundation",r:"seattle",a:"Pike Place Market",c:["hunger","community"],u:"https://pikeplacemarketfoundation.org",d:"Supports the Market's food bank, clinic and senior center — Sunset Supper & events."},
{n:"Operation Sack Lunch",r:"seattle",a:"Downtown Seattle",c:["hunger"],u:"https://oslseattle.org",d:"Prepares 1,000+ meals daily from scratch — kitchen prep and serving shifts."},
{n:"Little Bit Therapeutic Riding Center",r:"eastside",a:"Redmond & Woodinville",c:["health","animals"],u:"https://littlebit.org",d:"Adaptive horseback riding for people with disabilities — sidewalkers and horse leaders."},
{n:"REACH Center of Hope",r:"south",a:"Renton",c:["housing"],u:"https://reachrenton.org",d:"Renton's day center and emergency shelter for families — meal and supply support."},
{n:"RAYS (Renton Area Youth & Family Services)",r:"south",a:"Renton",c:["youth","health"],u:"https://rays.org",d:"Mental health and family services in Renton — board, events and program support."},
];
